[project]
name = "wechat2md"
version = "0.1.0"
description = "将微信公众号文章转换为 Markdown 格式。"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "html2text>=2025.4.15",
    "requests>=2.32.5",
]

[project.scripts]
# 定义全局命令名为 wechat2md
# wechat2md.py 脚本中必须有一个名为 main 的函数
wechat2md = "wechat2md:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"